[[commands]]
key = "lh"
value = "lh"

[commands.sub_commands]

[[commands]]
key = "lh"
value = "lh"

[commands.sub_commands]

[[commands]]
key = "lh"
value = "lh"

[commands.sub_commands]

[[commands]]
key = "helix"
value = "helix"

[commands.sub_commands]
